/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

import backend.Circulo;
import backend.Cuadrado;
import backend.Triangulo;
import java.awt.BorderLayout;
import java.awt.Container;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.bson.Document;

/**
 *
 * @author labctr
 */
public class ListaJPanel extends javax.swing.JPanel {
    
    private JPanel JPanelLista;
    private ListaCirculoJPanel listaCirculoPanel;

    /**
     * Creates new form ListaJPanel
     */
    public ListaJPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTriangulo = new javax.swing.JLabel();
        jLabelCuadrado = new javax.swing.JLabel();
        jLabelCirculo = new javax.swing.JLabel();
        jPanelLista = new javax.swing.JPanel();

        jLabelTriangulo.setIcon(new javax.swing.ImageIcon("C:/Users/toapa/Downloads/AreasFigurasDise-osGraficos_2capas-main/src/main/java/resources/Triangulo.png"));
        jLabelTriangulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTrianguloMouseClicked(evt);
            }
        });

        jLabelCuadrado.setIcon(new javax.swing.ImageIcon("C:/Users/toapa/Downloads/AreasFigurasDise-osGraficos_2capas-main/src/main/java/resources/Cuadrado.png"));
        jLabelCuadrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCuadradoMouseClicked(evt);
            }
        });

        jLabelCirculo.setIcon(new javax.swing.ImageIcon("C:/Users/toapa/Downloads/AreasFigurasDise-osGraficos_2capas-main/src/main/java/resources/Circulo.png"));
        jLabelCirculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCirculoMouseClicked(evt);
            }
        });

        jPanelLista.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelListaLayout = new javax.swing.GroupLayout(jPanelLista);
        jPanelLista.setLayout(jPanelListaLayout);
        jPanelListaLayout.setHorizontalGroup(
            jPanelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelListaLayout.setVerticalGroup(
            jPanelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabelTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jLabelCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jLabelCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addComponent(jPanelLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCirculo, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(jLabelCuadrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanelLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCirculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCirculoMouseClicked
    // Realizar la consulta de áreas de círculos
    List<Document> areasCirculos = new Circulo(0).consultarAreas();

    // Mostrar los datos en la tabla correspondiente (reemplaza con el nombre correcto de tu panel)
    ListaCirculoJPanel listaCirculoPanel = new ListaCirculoJPanel(areasCirculos);
    listaCirculoPanel.setSize(490, 300);
    listaCirculoPanel.setLocation(0, 0);
    jPanelLista.removeAll();
    jPanelLista.add(listaCirculoPanel, BorderLayout.CENTER);
    jPanelLista.revalidate();
    jPanelLista.repaint();
    }//GEN-LAST:event_jLabelCirculoMouseClicked

    private void jLabelCuadradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCuadradoMouseClicked
   // Realizar la consulta de áreas de cuadrados
    List<Document> areasCuadrados = new Cuadrado(0).consultarAreas();

    // Mostrar los datos en la tabla correspondiente (reemplaza con el nombre correcto de tu panel)
    ListaCuadradoJPanel listaCuadradoPanel = new ListaCuadradoJPanel(areasCuadrados);
    listaCuadradoPanel.setSize(490, 300);
    listaCuadradoPanel.setLocation(0, 0);
    jPanelLista.removeAll();
    jPanelLista.add(listaCuadradoPanel, BorderLayout.CENTER);
    jPanelLista.revalidate();
    jPanelLista.repaint();
    }//GEN-LAST:event_jLabelCuadradoMouseClicked

    private void jLabelTrianguloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTrianguloMouseClicked
     // Realizar la consulta de áreas de triángulos
    List<Document> areasTriangulos = new Triangulo(0, 0).consultarAreas();

    // Mostrar los datos en la tabla correspondiente
    ListaTrianguloJPanel listaTrianguloPanel = new ListaTrianguloJPanel(areasTriangulos);
    listaTrianguloPanel.setSize(490, 300);
    listaTrianguloPanel.setLocation(0, 0);
    jPanelLista.removeAll();
    jPanelLista.add(listaTrianguloPanel, BorderLayout.CENTER);
    jPanelLista.revalidate();
    jPanelLista.repaint();
    }//GEN-LAST:event_jLabelTrianguloMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCirculo;
    private javax.swing.JLabel jLabelCuadrado;
    private javax.swing.JLabel jLabelTriangulo;
    private javax.swing.JPanel jPanelLista;
    // End of variables declaration//GEN-END:variables
}
