/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/**
 *
 * @author PC
 */
public class ListaCirculoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ListaCirculoJPanel
     */
     public ListaCirculoJPanel(List<Document> areasCirculo) {
        initComponents();
        mostrarDatos(areasCirculo);
    }

      private void mostrarDatos(List<Document> areasCirculo) {
        DefaultTableModel modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("#");
        modeloTabla.addColumn("Radio");
        modeloTabla.addColumn("Área");

        int numeroFila = 1;
        for (Document area : areasCirculo) {
            double radio = area.getDouble("radio");
            double areaValor = area.getDouble("area");

            modeloTabla.addRow(new Object[]{numeroFila, radio, areaValor});
            numeroFila++;
        }

        jTableCirculo.setModel(modeloTabla);
    }
     
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCirculo = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jTableCirculo.setForeground(new java.awt.Color(52, 162, 240));
        jTableCirculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "#", "Radio", "Área"
            }
        ));
        jScrollPane1.setViewportView(jTableCirculo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCirculo;
    // End of variables declaration//GEN-END:variables
}
