/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/**
 *
 * @author PC
 */
public class ListaCuadradoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ListaCuadradoJPanel
     */
     public ListaCuadradoJPanel(List<Document> areasCuadrados) {
        initComponents();
        cargarTabla(areasCuadrados);
    }

    private void cargarTabla(List<Document> areasCuadrados) {
        DefaultTableModel modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("#");
        modeloTabla.addColumn("Lado");
        modeloTabla.addColumn("Área");

        for (int i = 0; i < areasCuadrados.size(); i++) {
            Document area = areasCuadrados.get(i);
            modeloTabla.addRow(new Object[]{i + 1, area.getDouble("lado"), area.getDouble("area")});
        }

        jTableCuadrado.setModel(modeloTabla);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCuadrado = new javax.swing.JTable();

        jTableCuadrado.setForeground(new java.awt.Color(52, 162, 240));
        jTableCuadrado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "#", "Lado", "Área"
            }
        ));
        jScrollPane1.setViewportView(jTableCuadrado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCuadrado;
    // End of variables declaration//GEN-END:variables
}
