/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import java.awt.BorderLayout;

/**
 *
 * @author toapa
 */
public class MenuJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuJFrame
     */
    private MenuJPanel jpanelMenu;
    public MenuJFrame() {
        initComponents();
        jpanelMenu= new MenuJPanel();
        jpanelMenu.setSize(jPanelVista.getSize());
        jpanelMenu.setLocation(0, 0);
        jPanelVista.removeAll();
        jPanelVista.add(jpanelMenu);
        jPanelVista.revalidate();
        jPanelVista.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonTriangulo = new javax.swing.JButton();
        jButtonCuadrado = new javax.swing.JButton();
        jButtonCirculo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jPanelVista = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButtonLista = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonTriangulo.setBackground(new java.awt.Color(247, 243, 236));
        jButtonTriangulo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButtonTriangulo.setForeground(new java.awt.Color(52, 162, 240));
        jButtonTriangulo.setText("Área Triangulo");
        jButtonTriangulo.setBorder(null);
        jButtonTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrianguloActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonTriangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 210, 40));

        jButtonCuadrado.setBackground(new java.awt.Color(247, 243, 236));
        jButtonCuadrado.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButtonCuadrado.setForeground(new java.awt.Color(52, 162, 240));
        jButtonCuadrado.setText("Área Cuadrado");
        jButtonCuadrado.setBorder(null);
        jButtonCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuadradoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCuadrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 210, 40));

        jButtonCirculo.setBackground(new java.awt.Color(247, 243, 236));
        jButtonCirculo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButtonCirculo.setForeground(new java.awt.Color(52, 162, 240));
        jButtonCirculo.setText("Área Círculo");
        jButtonCirculo.setBorder(null);
        jButtonCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCirculoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCirculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 210, 40));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(52, 162, 240));
        jLabel1.setText("MENÚ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 60, 30));

        jPanel2.setBackground(new java.awt.Color(52, 162, 240));

        jButtonSalir.setBackground(new java.awt.Color(247, 243, 236));
        jButtonSalir.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(52, 162, 240));
        jButtonSalir.setText("Salir");
        jButtonSalir.setBorder(null);
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(362, Short.MAX_VALUE)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 500, 30));

        jPanelVista.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVista.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jPanelVistaComponentAdded(evt);
            }
        });

        jLabel2.setText("AREAS");

        jTextPane1.setText("El concepto de \"área\" se refiere a la medida de la extensión de una superficie en dos dimensiones. En matemáticas y geometría, el área es una medida cuantitativa que describe cuánto espacio ocupa una figura en un plano. El cálculo del área es fundamental en diversos campos, incluyendo la geometría, la física, la ingeniería y otras disciplinas científicas.");
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanelVistaLayout = new javax.swing.GroupLayout(jPanelVista);
        jPanelVista.setLayout(jPanelVistaLayout);
        jPanelVistaLayout.setHorizontalGroup(
            jPanelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVistaLayout.createSequentialGroup()
                .addGap(2262, 2262, 2262)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelVistaLayout.createSequentialGroup()
                    .addGap(906, 906, 906)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1116, Short.MAX_VALUE)))
        );
        jPanelVistaLayout.setVerticalGroup(
            jPanelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVistaLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addContainerGap(350, Short.MAX_VALUE))
            .addGroup(jPanelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelVistaLayout.createSequentialGroup()
                    .addGap(123, 123, 123)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(143, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanelVista, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 490, 410));

        jButtonLista.setBackground(new java.awt.Color(247, 243, 236));
        jButtonLista.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonLista.setForeground(new java.awt.Color(52, 162, 240));
        jButtonLista.setText("Lista Áreas");
        jButtonLista.setBorder(null);
        jButtonLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 210, 40));

        jButton2.setBackground(new java.awt.Color(247, 243, 236));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(52, 162, 240));
        jButton2.setText("Eliminar Áreas");
        jButton2.setBorder(null);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 210, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:/Users/toapa/Downloads/AreasFigurasDise-osGraficos_2capas-main/src/main/java/resources/Fondo.png"));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 210, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrianguloActionPerformed
         TrianguloJPanel jpanelTriangulo = new TrianguloJPanel();

    // Configurar el tamaño y la posición del panelTriangulo
    jpanelTriangulo.setSize(jPanelVista.getSize());
    jpanelTriangulo.setLocation(0, 0);

    // Agregar el panelTriangulo al jPanelVista
    jPanelVista.removeAll();
    jPanelVista.add(jpanelTriangulo);
    jPanelVista.revalidate();
    jPanelVista.repaint();    
    }//GEN-LAST:event_jButtonTrianguloActionPerformed

    private void jButtonCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuadradoActionPerformed
      CuadradoJPanel jpanelCuadrado = new CuadradoJPanel();
      jpanelCuadrado.setSize(jPanelVista.getSize());
      jpanelCuadrado.setLocation(0, 0);
      
      jPanelVista.removeAll();
      jPanelVista.add(jpanelCuadrado);
      jPanelVista.revalidate();
      jPanelVista.repaint();
    }//GEN-LAST:event_jButtonCuadradoActionPerformed

    private void jButtonCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCirculoActionPerformed
        CirculoJPanel jpanelCirculo = new CirculoJPanel();
      jpanelCirculo.setSize(jPanelVista.getSize());
      jpanelCirculo.setLocation(0, 0);
      
      jPanelVista.removeAll();
      jPanelVista.add(jpanelCirculo);
      jPanelVista.revalidate();
      jPanelVista.repaint();
    }//GEN-LAST:event_jButtonCirculoActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jPanelVistaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jPanelVistaComponentAdded

    }//GEN-LAST:event_jPanelVistaComponentAdded

    private void jButtonListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListaActionPerformed
      ListaJPanel jpanelLista = new ListaJPanel();
      jpanelLista.setSize(jPanelVista.getSize());
      jpanelLista.setLocation(0, 0);
      
      jPanelVista.removeAll();
      jPanelVista.add(jpanelLista);
      jPanelVista.revalidate();
      jPanelVista.repaint();
    }//GEN-LAST:event_jButtonListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCirculo;
    private javax.swing.JButton jButtonCuadrado;
    private javax.swing.JButton jButtonLista;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonTriangulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelVista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
